export const Images = {
    IMG_APP_LOGO_THEME: require('../assets/images/app_logo_theme.png'),
    IMG_APP_LOGO_WHITE: require('../assets/images/app_logo_white.png'),
    IMG_BASKET: require('../assets/images/basket.png'),
    IMG_CALENDAR: require('../assets/images/calendar.png'),
    IMG_CARRY_BAG: require('../assets/images/carry_bag.png'),
    IMG_DIAMOND: require('../assets/images/diamond.png'),
    IMG_FOLDED_MAP: require('../assets/images/folded_map.png'),
    IMG_MENU: require('../assets/images/menu.png'),
    IMG_PALETTE: require('../assets/images/palette.png'),
    IMG_PIE_CHART: require('../assets/images/pie_chart.png'),
    IMG_RECTANGLE: require('../assets/images/rectangle.png'),
    IMG_SPACESHIP: require('../assets/images/spaceship.png'),
    IMG_WELCOME_SCREEN_BACKGROUND: require('../assets/images/welcome_screen_background.png'),
    IMG_SEARCH_ICON: require('../assets/images/search_icon.png'),
    IMG_NOTIFICATION_BELL: require('../assets/images/notification_bell.png'),
    IMG_FEMALE_MODAL_FEED: require('../assets/images/female_modal.png'),
    IMG_MALE_MODAL_FEED: require('../assets/images/male_modal.png'),
    IMG_ICECREAM_FEED: require('../assets/images/ice_cream_feed.png'),
    IMG_MACKUP_FEED: require('../assets/images/mackup_feed.png'),
    IMG_HILLS_FEED: require('../assets/images/hills_feed.png'),
}